id: I9FF2B59B
initial_creation_type: ebook
source_metadata:
  id: BEN-LB-013
  title: མཁས་གྲུབ་རྭ་ག་ཨ་སྱས་མཛད་པའི་རྣམ་དག་བདེ་ཆེན་ཞིང་གི་སྨོན་ལམ་དང་དེའི་འགྲེལ་པ་ཁག་ཕྱོགས་གཅིག་ཏུ་བསྒྲིབས་པ་གསོལ་བཏབ་མི་བསླུ་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  author: མཛད་པ་པོ། མཁས་གྲུབ་ཀརྨ་ཆགས་མེད།, ཛ་དཔལ་སྤྲུལ་རིན་པོ་ཆེ། མཁས་ཆེན་པདྨ་རྒྱལ།
    གཞན་ཕན་དཔལ་བཟང་།
  authors: &id001
  - མཛད་པ་པོ། མཁས་གྲུབ་ཀརྨ་ཆགས་མེད།
  - ཛ་དཔལ་སྤྲུལ་རིན་པོ་ཆེ། མཁས་ཆེན་པདྨ་རྒྱལ། གཞན་ཕན་དཔལ་བཟང་།
  sku: BEN-LB-013
  cover: 13th_Book_Cover.jpeg
  volume: {}
ebook_metadata:
  title: མཁས་གྲུབ་རྭ་ག་ཨ་སྱས་མཛད་པའི་རྣམ་དག་བདེ་ཆེན་ཞིང་གི་སྨོན་ལམ་དང་དེའི་འགྲེལ་པ་ཁག་ཕྱོགས་གཅིག་ཏུ་བསྒྲིབས་པ་གསོལ་བཏབ་མི་བསླུ་ཞེས་བྱ་བ་བཞུགས་སོ།
    །
  authors: *id001
  sku: BEN-LB-013
  cover: 13th_Book_Cover.jpeg
layers:
- Author
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
- Tsawa
- Yigchung
